import { z } from "zod";

/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * 
 * Generated by: scripts/sync-enums-to-contracts.ts
 * Generated at: 2026-01-02T18:10:55.334Z
 * 
 * These Zod schemas are synchronized from Prisma enum definitions.
 * To update, run: npm run sync:enums
 */

// Source: enums.prisma
export const PrismaThemeStatusSchema = z.enum(["DRAFT", "PRIVATE", "PENDING_APPROVAL", "PUBLISHED", "REJECTED"]);
export type PrismaThemeStatus = z.infer<typeof PrismaThemeStatusSchema>;

// Kebab-case version for DSL compatibility
export const PrismaThemeStatusSchemaKebab = z.enum(["draft", "private", "pending-approval", "published", "rejected"]);
export type PrismaThemeStatusKebab = z.infer<typeof PrismaThemeStatusSchemaKebab>;

// Mapping functions
export const themeStatusToKebab = (value: PrismaThemeStatus): PrismaThemeStatusKebab => {
  const mapping: Record<PrismaThemeStatus, PrismaThemeStatusKebab> = {
    "DRAFT": "draft",
    "PRIVATE": "private",
    "PENDING_APPROVAL": "pending-approval",
    "PUBLISHED": "published",
    "REJECTED": "rejected",
  };
  return mapping[value];
};

export const themeStatusFromKebab = (value: PrismaThemeStatusKebab): PrismaThemeStatus => {
  const mapping: Record<PrismaThemeStatusKebab, PrismaThemeStatus> = {
    "draft": "DRAFT",
    "private": "PRIVATE",
    "pending-approval": "PENDING_APPROVAL",
    "published": "PUBLISHED",
    "rejected": "REJECTED",
  };
  return mapping[value];
};

// Source: enums.prisma
export const PrismaThemeCategorySchema = z.enum(["PROFESSIONAL", "CREATIVE", "TECHNICAL", "ACADEMIC", "MINIMAL", "MODERN", "CLASSIC", "EXECUTIVE"]);
export type PrismaThemeCategory = z.infer<typeof PrismaThemeCategorySchema>;

// Kebab-case version for DSL compatibility
export const PrismaThemeCategorySchemaKebab = z.enum(["professional", "creative", "technical", "academic", "minimal", "modern", "classic", "executive"]);
export type PrismaThemeCategoryKebab = z.infer<typeof PrismaThemeCategorySchemaKebab>;

// Mapping functions
export const themeCategoryToKebab = (value: PrismaThemeCategory): PrismaThemeCategoryKebab => {
  const mapping: Record<PrismaThemeCategory, PrismaThemeCategoryKebab> = {
    "PROFESSIONAL": "professional",
    "CREATIVE": "creative",
    "TECHNICAL": "technical",
    "ACADEMIC": "academic",
    "MINIMAL": "minimal",
    "MODERN": "modern",
    "CLASSIC": "classic",
    "EXECUTIVE": "executive",
  };
  return mapping[value];
};

export const themeCategoryFromKebab = (value: PrismaThemeCategoryKebab): PrismaThemeCategory => {
  const mapping: Record<PrismaThemeCategoryKebab, PrismaThemeCategory> = {
    "professional": "PROFESSIONAL",
    "creative": "CREATIVE",
    "technical": "TECHNICAL",
    "academic": "ACADEMIC",
    "minimal": "MINIMAL",
    "modern": "MODERN",
    "classic": "CLASSIC",
    "executive": "EXECUTIVE",
  };
  return mapping[value];
};

// Source: enums.prisma
export const PrismaTechAreaTypeSchema = z.enum(["DEVELOPMENT", "DEVOPS", "DATA", "SECURITY", "DESIGN", "PRODUCT", "QA", "INFRASTRUCTURE", "OTHER"]);
export type PrismaTechAreaType = z.infer<typeof PrismaTechAreaTypeSchema>;

// Kebab-case version for DSL compatibility
export const PrismaTechAreaTypeSchemaKebab = z.enum(["development", "devops", "data", "security", "design", "product", "qa", "infrastructure", "other"]);
export type PrismaTechAreaTypeKebab = z.infer<typeof PrismaTechAreaTypeSchemaKebab>;

// Mapping functions
export const techAreaTypeToKebab = (value: PrismaTechAreaType): PrismaTechAreaTypeKebab => {
  const mapping: Record<PrismaTechAreaType, PrismaTechAreaTypeKebab> = {
    "DEVELOPMENT": "development",
    "DEVOPS": "devops",
    "DATA": "data",
    "SECURITY": "security",
    "DESIGN": "design",
    "PRODUCT": "product",
    "QA": "qa",
    "INFRASTRUCTURE": "infrastructure",
    "OTHER": "other",
  };
  return mapping[value];
};

export const techAreaTypeFromKebab = (value: PrismaTechAreaTypeKebab): PrismaTechAreaType => {
  const mapping: Record<PrismaTechAreaTypeKebab, PrismaTechAreaType> = {
    "development": "DEVELOPMENT",
    "devops": "DEVOPS",
    "data": "DATA",
    "security": "SECURITY",
    "design": "DESIGN",
    "product": "PRODUCT",
    "qa": "QA",
    "infrastructure": "INFRASTRUCTURE",
    "other": "OTHER",
  };
  return mapping[value];
};

// Source: enums.prisma
export const PrismaSkillTypeSchema = z.enum(["LANGUAGE", "FRAMEWORK", "LIBRARY", "DATABASE", "TOOL", "PLATFORM", "METHODOLOGY", "SOFT_SKILL", "CERTIFICATION", "OTHER"]);
export type PrismaSkillType = z.infer<typeof PrismaSkillTypeSchema>;

// Kebab-case version for DSL compatibility
export const PrismaSkillTypeSchemaKebab = z.enum(["language", "framework", "library", "database", "tool", "platform", "methodology", "soft-skill", "certification", "other"]);
export type PrismaSkillTypeKebab = z.infer<typeof PrismaSkillTypeSchemaKebab>;

// Mapping functions
export const skillTypeToKebab = (value: PrismaSkillType): PrismaSkillTypeKebab => {
  const mapping: Record<PrismaSkillType, PrismaSkillTypeKebab> = {
    "LANGUAGE": "language",
    "FRAMEWORK": "framework",
    "LIBRARY": "library",
    "DATABASE": "database",
    "TOOL": "tool",
    "PLATFORM": "platform",
    "METHODOLOGY": "methodology",
    "SOFT_SKILL": "soft-skill",
    "CERTIFICATION": "certification",
    "OTHER": "other",
  };
  return mapping[value];
};

export const skillTypeFromKebab = (value: PrismaSkillTypeKebab): PrismaSkillType => {
  const mapping: Record<PrismaSkillTypeKebab, PrismaSkillType> = {
    "language": "LANGUAGE",
    "framework": "FRAMEWORK",
    "library": "LIBRARY",
    "database": "DATABASE",
    "tool": "TOOL",
    "platform": "PLATFORM",
    "methodology": "METHODOLOGY",
    "soft-skill": "SOFT_SKILL",
    "certification": "CERTIFICATION",
    "other": "OTHER",
  };
  return mapping[value];
};

// Source: enums.prisma
export const PrismaResumeTemplateSchema = z.enum(["PROFESSIONAL", "CREATIVE", "TECHNICAL", "MINIMAL", "MODERN", "EXECUTIVE", "ACADEMIC"]);
export type PrismaResumeTemplate = z.infer<typeof PrismaResumeTemplateSchema>;

// Kebab-case version for DSL compatibility
export const PrismaResumeTemplateSchemaKebab = z.enum(["professional", "creative", "technical", "minimal", "modern", "executive", "academic"]);
export type PrismaResumeTemplateKebab = z.infer<typeof PrismaResumeTemplateSchemaKebab>;

// Mapping functions
export const resumeTemplateToKebab = (value: PrismaResumeTemplate): PrismaResumeTemplateKebab => {
  const mapping: Record<PrismaResumeTemplate, PrismaResumeTemplateKebab> = {
    "PROFESSIONAL": "professional",
    "CREATIVE": "creative",
    "TECHNICAL": "technical",
    "MINIMAL": "minimal",
    "MODERN": "modern",
    "EXECUTIVE": "executive",
    "ACADEMIC": "academic",
  };
  return mapping[value];
};

export const resumeTemplateFromKebab = (value: PrismaResumeTemplateKebab): PrismaResumeTemplate => {
  const mapping: Record<PrismaResumeTemplateKebab, PrismaResumeTemplate> = {
    "professional": "PROFESSIONAL",
    "creative": "CREATIVE",
    "technical": "TECHNICAL",
    "minimal": "MINIMAL",
    "modern": "MODERN",
    "executive": "EXECUTIVE",
    "academic": "ACADEMIC",
  };
  return mapping[value];
};

// Combined types for convenience
export const PrismaEnums = {
  ThemeStatus: PrismaThemeStatusSchema,
  ThemeCategory: PrismaThemeCategorySchema,
  TechAreaType: PrismaTechAreaTypeSchema,
  SkillType: PrismaSkillTypeSchema,
  ResumeTemplate: PrismaResumeTemplateSchema,
} as const;

export const PrismaEnumsKebab = {
  ThemeStatus: PrismaThemeStatusSchemaKebab,
  ThemeCategory: PrismaThemeCategorySchemaKebab,
  TechAreaType: PrismaTechAreaTypeSchemaKebab,
  SkillType: PrismaSkillTypeSchemaKebab,
  ResumeTemplate: PrismaResumeTemplateSchemaKebab,
} as const;
